---
apiVersion: "wso2.com/v1alpha2"
kind: "Integration"
metadata:
  name: "sample-integration"
spec:
  image: "arunans23/sample-integration:1.0.8"
  deploySpec:
    minReplicas: 1
  envFrom:
  - configMapRef:
      name: "env-data"
